Comment out idPlayer::AI_ATTACK2_HELD script bool
it caused an assertion (`assert(data)`) when starting a level because
it wasn't linked. when linking it it causes
> ERROR: Missing 'AI_ATTACK2_HELD' field in script object 'player'
which indicates that the scripts don't support it, so I just commented
it out completely